### ISSUE TITLE
Ghost Overrides not working right

### ISSUE THREAD

**Issue by johnjelinek** [dockerfile/ghost#1]
When I add a theme to my `ghost-overrides` volume, it doesn't propagate to my new container. It isn't detected in the general settings.

**Comment by pilwon** [comment]
@johnjelinek Double check if you placed your theme files in `content/themes` and make sure `ghost-override` is not plural. (drop `s` at the end)

**Comment by pilwon** [comment]
@johnjelinek and you can always look inside your container with `docker run -i -t -p 80:2368 -v <override-dir>:/ghost-override dockerfile/ghost bash` to understand what's really going on.

**Comment by brishin** [comment]
@pilwon The `start.bash` script is not symlinking and overwriting the files in `/ghost` properly. This can be seen after  viewing in bash. Only `content/data` is being copied over correctly.

**Comment by oyvindsk** [comment]
yeah, I got this as well. The cp command gives:

```
cp: cannot stat `/ghost-override/*': No such file or directory
```

for some reason. 

Doing it "manually" works
[ edit: what I had here was not enough.. now I just symlink the whole content directory.. ]

**Comment by etx** [comment]
I'm having the same issue as well.

**Comment by EpocSquadron** [comment]
I am also having this issue. It seems it symlinks the data directory, but nothing else. When I execute the `cp -frs /ghost-override/* /ghost/` command manually, it prompts to overrides config.js despite the -f flag being specified. Since stderr is going to /dev/null, it jst continues on as if it succeeded.
